-- #2988
alter table RAD_STE
ADD EXT TEXT;

-- #3321
DROP INDEX IF EXISTS IDX_ACS_TKN_EXP_ON;
DROP INDEX IF EXISTS IDX_AUD_TS;

CREATE INDEX IDX_ACS_TKN_EXP_ON ON ACS_TKN(EXP_ON);
CREATE INDEX IDX_AUD_TS ON AUD(TS);

ALTER TABLE AUD_PRM DROP CONSTRAINT AUD_PRM_R_AUD_FKEY;

CREATE OR REPLACE PROCEDURE CLEAR_ACS_TKN(
    IN BATCH_SIZE INT DEFAULT 10000
  )
  LANGUAGE PLPGSQL
  AS $$
  DECLARE
    ROWS_AFFECTED INT;
    ROWS_TOTAL INT := 0;
  BEGIN
    LOOP
      DELETE FROM ACS_TKN WHERE ID IN (SELECT ID FROM ACS_TKN WHERE EXP_ON < EXTRACT(EPOCH FROM NOW()) LIMIT BATCH_SIZE);            
      GET DIAGNOSTICS ROWS_AFFECTED = ROW_COUNT;

      ROWS_TOTAL := ROWS_TOTAL + ROWS_AFFECTED;
  
      EXIT WHEN ROWS_AFFECTED = 0;
            
      COMMIT;
      PERFORM PG_SLEEP(0.1);
      END LOOP;
      RAISE NOTICE 'ACS_TKN ROWS DELETED: %', ROWS_TOTAL;
  END;
$$;

CREATE OR REPLACE PROCEDURE CLEAR_RFR_TKN(
    IN BATCH_SIZE INT DEFAULT 10000    
  )
  LANGUAGE PLPGSQL
  AS $$
  DECLARE
    ROWS_AFFECTED INT;
    ROWS_TOTAL INT := 0;
  BEGIN
    LOOP
      DELETE FROM RFR_TKN WHERE ID IN (SELECT ID FROM RFR_TKN WHERE EXP_ON < EXTRACT(EPOCH FROM NOW()) LIMIT BATCH_SIZE);
      GET DIAGNOSTICS ROWS_AFFECTED = ROW_COUNT;
      
      ROWS_TOTAL := ROWS_TOTAL + ROWS_AFFECTED;
      
      EXIT WHEN ROWS_AFFECTED = 0;
            
      COMMIT;
      PERFORM PG_SLEEP(0.1);
      END LOOP;

      RAISE NOTICE 'RFR_TKN ROWS DELETED: %', ROWS_TOTAL;
  END;
$$;

CREATE OR REPLACE PROCEDURE CLEAR_AUD(
    IN BATCH_SIZE INT DEFAULT 10000,
    IN DAYS_COUNT INT DEFAULT 30 
  )
  LANGUAGE PLPGSQL
  AS $$
  DECLARE
    ROWS_AFFECTED INT;
    AUD_TOTAL INT := 0;
    AUD_PRM_TOTAL INT := 0;
  BEGIN
    LOOP
      DELETE FROM AUD_PRM WHERE R_AUD IN (SELECT R_AUD FROM AUD_PRM WHERE TS <= EXTRACT(EPOCH FROM NOW() - (interval '1 day' * DAYS_COUNT)) LIMIT BATCH_SIZE);
      GET DIAGNOSTICS ROWS_AFFECTED = ROW_COUNT;
      
      AUD_TOTAL := AUD_TOTAL + ROWS_AFFECTED;
      DELETE FROM AUD WHERE ID IN (SELECT ID FROM AUD WHERE TS <= EXTRACT(EPOCH FROM NOW() - (interval '1 day' * DAYS_COUNT)) LIMIT BATCH_SIZE);
      GET DIAGNOSTICS ROWS_AFFECTED = ROW_COUNT;
      
      AUD_PRM_TOTAL := AUD_PRM_TOTAL + ROWS_AFFECTED;
      EXIT WHEN ROWS_AFFECTED = 0;
      
      COMMIT;
      PERFORM PG_SLEEP(0.1);
    END LOOP;
    RAISE NOTICE 'AUD ROWS DELETED: %', AUD_TOTAL;
    RAISE NOTICE 'AUD_PRM ROWS DELETED: %', AUD_PRM_TOTAL;
END;
$$;


INSERT INTO BLITZ_SCHEMA_VERSION (SCRIPT_NAME, DATE) VALUES ('027-5.30.0.sql', LOCALTIMESTAMP(2));
