-- #3319 added node and source columns

ALTER TABLE AUD
ADD COLUMN NODE text,
ADD COLUMN SRC text,
ADD COLUMN SRC_VER text;

-- #3144

ALTER TABLE ACS_TKN
ADD COLUMN OFL BOOLEAN,
ADD COLUMN SES_ID TEXT,
ADD COLUMN UA_ID TEXT,
ADD COLUMN UA_VER TEXT;

ALTER TABLE ACS_TKN DROP COLUMN CRID;

ALTER TABLE RFR_TKN
ADD COLUMN OFL BOOLEAN,
ADD COLUMN SES_ID TEXT,
ADD COLUMN UA_ID TEXT,
ADD COLUMN UA_VER TEXT;

ALTER TABLE RFR_TKN DROP COLUMN CRID;

ALTER TABLE USR_PRP DROP COLUMN CRID;

-- #3142

CREATE TABLE SES (
	ID TEXT NOT NULL,
	SBJ_ID TEXT NOT NULL,
	UA_ID TEXT,
	UA_VER TEXT,
	CRT_ON INT4 NOT NULL,
	LST_ACT INT4 NOT NULL,
	EXP_ON INT4 NOT NULL,
	BND_TO TEXT NOT NULL,
	CONSTRAINT SES_ID_PK PRIMARY KEY (ID)
);

ALTER TABLE USR_AGT RENAME COLUMN TTL TO EXP_ON;
ALTER TABLE USR_AGT ADD COLUMN CRT_ON INT4 NULL;

-- #3163
ALTER TABLE SES ADD COLUMN CLMS TEXT;
ALTER TABLE RFR_TKN ADD COLUMN CLMS TEXT;

-- #3332
ALTER TABLE REG ADD COLUMN PRM TEXT;

-- #3457
ALTER TABLE USR ADD COLUMN EXPIRES_AT TEXT;
ALTER TABLE USR_ATR ADD COLUMN EXPIRES_AT TEXT;

INSERT INTO BLITZ_SCHEMA_VERSION (SCRIPT_NAME, DATE) VALUES ('028-5.31.0.sql', LOCALTIMESTAMP(2));
